add hero-homepage
DarinaMerkulova/project-team-5 pull request #17
Opened 2023-02-18 00:54 UTC by alnesk

у меня неправильно сделаны картинки. поэтому всё поехало. можешь подсказать как правильно сделать картинки и вернуть обратно. я переделаю

2023-02-18 06:24 UTC, DarinaMerkulova requested changes

2023-02-18 06:24 UTC, DarinaMerkulova commented on src/css/homepage/hero-homepage.css
> +  }
Видали все до цього моменту, воно повинно підключитися із загальних стилів

2023-02-18 06:24 UTC, DarinaMerkulova commented on src/css/homepage/hero-homepage.css
> +    font-family: 'Montserrat';
Тут може залишити лише колір, усе інше підтягнеться із body

2023-02-18 06:24 UTC, DarinaMerkulova commented on src/css/homepage/hero-homepage.css
> +        url(../../img/mobile/Mob-homepage/mob-hero.jpg);
Я думаю, що шлях треба прописати ( ../іmg/), бо а в тебе шось багато крапок і /

2023-02-18 06:24 UTC, DarinaMerkulova commented on src/css/homepage/hero-homepage.css
> +    background: rgba(0, 0, 0, 0.4);
Background є в vars

2023-02-18 06:24 UTC, DarinaMerkulova commented on src/css/homepage/hero-homepage.css
> +    font-family: 'Montserrat';
Кругом, де є шрифт Montserrat, не треба його писати, так як він тягнеться із body. Тобто не повторюємо Font family, letter-spacing

2023-02-18 06:24 UTC, DarinaMerkulova commented on src/css/homepage/hero-homepage.css
> +        background-image: linear-gradient(to right, rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)),
Градієнт теж є в загальному класів

2023-02-19 14:55 UTC, alnesk commented
я поубирал то что ты сказала. вроде мобильная версия выглядит так как надо, но при переходе на компьютерную версию 
начинают ехать картинки, а из-за этого плывёт текст

2023-02-19 15:28 UTC, merged